- name: Loop packages
  hosts: forntend
  become: yes

  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mongodb-mongosh
        - mysql
        - git