- name: loops package
  hosts: forntend
  becmode: yes
  tasks:
  - name: intall packages
    package: 
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mongodb-mongosh
    - mqsql
    - git