
- name: demo on variables
  hosts: localhost
  connection: local

  vars:
    course: "Ansible"
    trainer: "vijay"
    duration: "150hrs"

  tasks:
    - debug:
        msg: "Hi I am learning {{ course }} with {{ trainer }} advance course, {{ duration }}"