- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux,Shell,Ansible
    tagmap:
     name: Ansible
     project: roboshop
     environment: dev
    full_Name: Vijayabhaskar
    taglist: [
     {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "environment",
            "value": "dev"
        }
    ]
  tasks:
  - name: topics convert to list
    debug:
      msg: "Topics are{{topics | split(',')}}"

  - name: default values
    debug:
      msg: "Hi {{Greeting | default('Good Morning')}}"

  - name: conver to list
    debug:
      msg: "{{tagmap | dict2items }}"

  - name: convert to map
    debug:
      msg: "{{taglist | items2dict}}"

  - name: Convert to Upper case
    debug:
      msg: "{{full_Name | upper}}"

  - name: Convert to Lower case
    debug:
      msg: "{{full_Name | lower}}"

