- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: "Linux","Shell","Ansible"
  tasks:
  - name: topics convert to list
    debug:
      msg: "Topics are{{topics | split(',')}}"