- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux,Shell,Ansible
    tagmap:
     name: Ansible
     project: roboshop
     environment: dev
  tasks:
  - name: topics convert to list
    debug:
      msg: "Topics are{{topics | split(',')}}"

  - name: default values
    debug:
      msg: "Hi {{Greeting | default('Good Morning')}}"

  - name: conver to list
    debug:
      msg: "{{tagmap | dict2items }}"

